config/routes.rb
BolsaDeEmpApp::Application.routes.draw do
root             'static_pages#home'

#backoffice
get 'backoffice'  => 'backoffice#home'
get 'editUsers' => 'backoffice#editUsers'
get 'editNoticias' => 'backoffice#editNoticias'
get 'backofficeDetalhesUser' => 'backoffice#detalhesUser'
get 'editUser' => 'backoffice#editUser'
get 'inserirUser' => 'backoffice#inserirUser'
get 'editPw' => 'backoffice#editPw'
get 'editNoticia' => 'backoffice#editNoticia'
get 'backofficeDetalhesNoticia' => 'backoffice#detalhesNoticia'
get 'inserirNoticia' => 'backoffice#inserirNoticia'



#users
resources :users do
  member do
    get :following, :followers
    get :userCandidates
  end
end
get 'showEntidades' => 'users#showEntidades'
get 'showCandidatos' => 'users#showCandidatos'
get 'editPwUser' => 'users#editPwUser'
post 'updatePW' => 'users#updatePW'
get 'perfilent' => 'users#perfilent'
get 'perfilcand' => 'users#perfilcand'
post 'candidatosignup'  => 'users#newCandidato'
post 'entidadesignup' => 'users#newEntidade'
get 'users/new'


#session
get 'sessions/new'
get 'signup'  => 'sessions#choose'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'

#offers
resources :offers
get 'offers/new'
get 'showOfertas' => 'offers#showOfertas'

#articles
resources :articles
get 'articles/new'
get 'showNoticias'  => 'articles#showNoticias'

#relationship
resources :relationships,       only: [:create, :destroy]

#Candidatures
resources :candidatures,       only: [:create, :destroy]
get 'candidatures/new'


#account activation
resources :account_activations, only: [:edit]

#password reset
resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

end

app/models/user.rb
class User < ActiveRecord::Base
  #assegurar que quando um utilizador for destruido tambem é destruida a oferta

  #novo modelo ofertas
  has_many :offers, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

#candidatarme
  has_many :active_candidatures, class_name: "Candidature",
                                 foreign_key: "user_id",
                                 dependent: :destroy

  has_many :userCandidates, through: :active_candidatures, source: :offer





  attr_accessor :remember_token, :activation_token, :reset_token
  #metodos antecedentes às açoes
  before_save   :downcase_email
  before_create :create_activation_digest
  #uploaders
  mount_uploader :picture, PictureUploader
  mount_uploader :cv, AttachmentUploader
  #validaçoes sql
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: "Email Inválido"  },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  validate  :picture_size
  validate  :cv_size

  VALID_CODP_REGEX = /([1-9][0-9]{3}-[1-9][0-9]{2})|([1-9][0-9]{3}-[a-zA-Z]{3,6})/i #exemplos validos :4485-710 4485-VCD ou vazio
  validates :codPostal, format: { with: VALID_CODP_REGEX, message: "inválido (ex: 4485-710 ou 4485-VCD ou vazio)" ,allow_nil: true ,allow_blank: true}
  validates :morada, length:{maximum:255,message: "ultrapassou os caracteres permitidos. (255 car.)"}
  validates :apresentacao, length:{maximum:356,message: "ultrapassou os caracteres permitidos. (356 car.)"}
  validates :habilitlit, length:{maximum:356,message: "ultrapassou os caracteres permitidos. (356 car.)"}
  validates :expProf, length:{maximum:356,message: "ultrapassou os caracteres permitidos. (356 car.)"}

=begin nao sao necessarios, sao escolhidos com droplist
  VALID_APROF_REGEX = /(Progamador Web|Eng de software|Eng de sistemas|outro)\z/i
  validates :areaprof, format: { with: VALID_APROF_REGEX , message: "Área profissional Inválida"}

  VALID_SITPROF_REGEX = /(Empregado|Desempregado)\z/i
  validates :situacaoprof, format: { with: VALID_SITPROF_REGEX , message: "Situação profissional Inválida"}

  VALID_ATIVIDADEPROF_REGEX = /(Progamador Web|Eng de software|Eng de sistemas|outro)\z/i
  validates :atividadeprofissional, format: { with: VALID_ATIVIDADEPROF_REGEX , message: "Área profissional Inválida"}
=end

  VALID_TEL_REGEX = /((91)|(92)|(93)|(94)|(95)|(96))[0-9]{7}/i
  validates :telemovel, format:{with: VALID_TEL_REGEX, message: " inválido" ,allow_nil: true ,allow_blank: true}

  VALID_BI_REGEX = /[0-9]{8}\z/i
  validates :bi, format:{with: VALID_BI_REGEX, message: " inválido" ,allow_nil: true ,allow_blank: true}

  VALID_NIF_REGEX = /[0-9]{9}\z/i
  validates :nif, format:{with: VALID_BI_REGEX, message: " inválido" ,allow_nil: true ,allow_blank: true}



  validates :paginaweb, format: { with: URI.regexp ,allow_nil: true ,allow_blank: true}
  validates :paginapessoal, format: { with: URI.regexp ,allow_nil: true ,allow_blank: true}


  #scopes para filtragem (search)

  scope :containent, -> (name,actividadeprofissional,localidade) { where("name like ? and tipouser='entidade' and actividadeprofissional like ? and localidade like ?", "%#{name}%","%#{actividadeprofissional}%","%#{localidade}%")}
  scope :containcand, -> (name,areaprof,situacaoprof,localidade) { where("name like ? and tipouser='candidato' and areaprof like ? and situacaoprof like ? and localidade like ?", "%#{name}%","%#{areaprof}%","%#{situacaoprof}%","%#{localidade}%")}
scope :contain, -> (name,tipo) { where("name like ?  and tipouser like ? ", "%#{name}%","%#{tipo}%")}



  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end


 # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end



  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Oferta.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)

  end




  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end



  # Follows a user.
  def candidatar(offer)
    active_candidatures.create(offer_id: offer.id)
  end

  # Unfollows a user.
  def descandidatar(offer)
    active_candidatures.find_by(offer_id: offer.id).destroy
  end

  # Returns true if the current user is following the other user.
  def userCandidates?(offer)

    userCandidates.include?(offer)
  end


##Private Methods bellow
private
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    # Validates the size of an uploaded picture.

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

    # Validates the size of an uploaded picture.
    def cv_size
      if cv.size > 5.megabytes
        errors.add(:cv, "should be less than 5MB")
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update ]
  before_action :admin_user,     only: :destroy

  include ApplicationHelper

  def self.search(search)
    if search
      @users=User.where('name LIKE ?', "%#{search}%")
    else

    end
  end


def index
@users = User.where.not(tipouser: "admin").paginate(page: params[:page],:per_page => 8)
end


def perfilent
@offersAtivas=current_user.offers.where(ativado: true).order(updated_at: :desc, created_at: :desc).paginate(page: params[:o_page],:per_page => 2)
@historicoOffers=current_user.offers.where(ativado: false).order(updated_at: :desc, created_at: :desc).paginate(page: params[:ho_page],:per_page => 2)
@candinteressados=current_user.followers.paginate(page: params[:c_page],:per_page => 2)
end
def perfilcand
@empinteressadas=current_user.followers.paginate(page: params[:e_page],:per_page => 2)
@candidaturas=current_user.userCandidates.paginate(page: params[:c_page],:per_page => 2)
end


def show
 @user = User.find(params[:id])
end

def showCandidatos
  @areasprof =User.uniq.pluck(:areaprof).reject{ |f| f.nil? || f.empty? }
  @localidades =User.where(tipouser: "candidato").uniq.pluck(:localidade).reject{ |f| f.nil? || f.empty? }
  @situacoesprof=User.where(tipouser: "candidato").uniq.pluck(:situacaoprof).reject{ |f| f.nil? || f.empty? }
  @users = User.where(tipouser: "candidato").containcand(params[:name],params[:areaprof],params[:situacaoprof],params[:localidade]).paginate(page: params[:page], :per_page => 8)
end

def showEntidades
  @atividadesprof =User.uniq.pluck(:actividadeprofissional).reject{ |f| f.nil? || f.empty? }
  @localidades =User.where(tipouser: "entidade").uniq.pluck(:localidade).reject{ |f| f.nil? || f.empty? }
  @users = User.containent(params[:name],params[:actividadeprofissional],params[:localidade]).paginate(page: params[:page], :per_page => 8)
end

def new
 @user = User.new
end


#cria um candidato valo tipouser = candidato
def newCandidato
@user= User.new
end

def newEntidade
@user= User.new
end

def create
@user = User.new(user_params)
    if @user.save
      if(@user.activated?)
      redirect_to @user
      else
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Verifique o seu email para ativar a conta."
      redirect_to root_url
      end
    else
      if logged_in? && current_user.tipouser=='admin'
        render 'backoffice/inserirUser'
      else
        if @user.tipouser=='entidade'
        render 'newEntidade'
        else
        render 'newCandidato'
        end
      end
    end
end

def edit
store_location
end

def editPwUser
 @user = User.find(current_user.id)
end

 def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil atualizado"
      redirect_to @user
    else
      render 'edit'
    end
end

 def updatePW
    @user = User.find(current_user.id)
    if @user.authenticate(params[:current_password]) && @user.update_attributes(user_params)
      flash[:success] = "Password atualizada"
      redirect_to @user
    else
      flash.now[:danger] = "Password atual incorreta" unless @user.authenticate(params[:current_password])
      render 'editPwUser'
    end
end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilizador removido"
    redirect_back_or(root_url)
  end

  def following
    @title = "A Seguir"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Seguidores"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end




    private

    def user_params
      params.require(:user).permit(:name,
                                    :email,
                                    :password,
                                   :password_confirmation,
                                   :tipouser,
                                   :picture,
                                   :cv,
                                   :morada,
                                   :localidade,
                                   :codPostal,
                                   :telemovel,
                                   :datadenasc,
                                   :paginapessoal,
                                   :bi,
                                   :areaprof,
                                   :apresentacao,
                                   :niveldehab,
                                   :habilitlit,
                                   :situacaoprof,
                                   :expProf,
                                   :fax,
                                   :nif,
                                   :actividadeprofissional,
                                   :paginaweb,
                                   :activated)
    end

# Before filters



end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_detalhesEntidade.html.erb
<% provide(:title, @user.name) %>

<aside class="col-md-3">

        <div class="col-md-12">
            <section class="user_info">
                <div class="col-md-12">
                  <h1><%= @user.name %></h1>
                </div>
                <!--imagem do utilizador se nao existir expoe uma por defeito-->
                <%= image_tag @user.picture.url if @user.picture?  %>
                <%= image_tag("man.png",size: "160x160") if !@user.picture?%>
                <br></br>
                <%if @user.cv?%>
                <span style="text-decoration: underline; color:blue"> <%=link_to "Curriculum Vitae", @user.cv.url %></span>
                <%end%>
                <%if logged_in?%>
                <% if current_user.tipouser == "admin" && !current_user?(@user) %>
                <%= link_to "Editar Perfil",  edit_user_path(@user), :class=>"btn btn-primary"%>
                <% end %>
                <% if current_user?(@user) %>
                <%= link_to "Editar Perfil",  edit_user_path(@user), :class=>"btn btn-primary"%>
                <% end %>
                <% end %>
                <br></br>
                  <!--seguidores-->
                   <div class="row col-md-12" >
                     <section class="stats">
                        <%if logged_in?%>
                        <%= render 'shared/stats' %>
                        <% end %>
                    </section>
                    </div>
                <br></br>
            </section>
        </div>

</aside>


    <div class="col-md-9 vert-offset-top-2">
       <%if @user.apresentacao?%> <b>Apresentação:</b>
        <br>
        <%=@user.apresentacao.html_safe%><br><br><%end%>
        <%if @user.actividadeprofissional?%><b>Actividade Profissional:</b><br>
        <%=@user.actividadeprofissional%><br><br><%end%>
        <%if @user.morada? || @user.codPostal?%><b>Morada:</b><br>
        <%if @user.morada?%><%=@user.morada.html_safe%><br><%end%>
        <%if @user.codPostal?%><%=@user.codPostal%><br><br><%end%><%end%>
        <b>Contactos:</b><br>
       <%if @user.telemovel?%> Tel: <%=@user.telemovel%><br><%end%>
       <%if @user.fax?%> Fax: <%=@user.fax%><br><%end%>
        Email: <%=@user.email%><br><br>
        <%if @user.paginaweb?%><b>Página:</b><br>
        <%=link_to @user.paginaweb%><%end%>
    </div>

<%if @user.offers.count>0%>
<div class="row">
    <div class="col-md-12">
        <%@offers=@user.offers.where(ativado: true).order(updated_at: :desc, created_at: :desc).paginate(page: params[:page],:per_page => 4) %>
        <h3>Ofertas Activas </h3><br>
        <%=render @offers%>
        <div class="col-md-12">
    <%= will_paginate @offers%>
    </div>
</div>

</div>
<%end%>
<div class="col-md-12 col-md-offset-5">
        <%if logged_in?%>
        <% if current_user.tipouser == "admin" && !current_user?(@user) %>
        <%= link_to "Inserir Nova Oferta",  offers_new_path, :class=>"btn btn-primary"%>
        <% end %>
        <% if current_user?(@user) %>
        <%= link_to "Inserir Nova Oferta",  offers_new_path, :class=>"btn btn-primary"%>
        <% end %>
        <%end%>
    </div>

      <div class="col-md-12">
    <%=link_to "Ver entidades", showEntidades_path%>
    </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Interessado/a", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form_<%= @user.id %>">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, url: users_url, as: 'user'  do |f| %>
<%= render 'shared/error_messages' %>
<div class="col-md-3">
  <%= f.input :name ,label: "Nome"%>
  <%= f.input :password, hint: false  %>
  <%= f.input :password_confirmation, label: "Confirma a password" %>
  <%= f.input :email, label: "Email" %>
  <%= f.input :datadenasc, label: "Data De Nascimento", :input_html => { :class => 'datepicker' } %>
  <!--falta por a foto-->
</div>
<div class="col-md-9">
  <%= f.input :morada, label: "Morada" %>
  <%= f.input :codPostal, label: "Codigo Postal" %>
  <%= f.input :telemovel, label: "Telemovel" %>
</div>
<!--colocar tinymce  para apresentaçao-->
<div class="col-md-6">
  <%= f.text_area :apresentacao,label: "Apresentação", :input_html => { :class => "textarea" } %>
  <%= f.input :niveldehab, label: "Nível de habilitações", as: :select,
  collection: [
  'Secundário',
  'Licenciado',
  'Mestre',
  'Doutorado'],
  :selected => 0
  %>
  <!--colocar tinymce  para habilitaçoes literarias-->
  <%= f.text_area :habilitlit,label: "Habilitações Literárias", :input_html => { :class => "textarea" } %>
  <%= f.input :situacaoprof, label: "Situação profissional", as: :select,
  collection: [
  'Empregado',
  'Desempregado'],
  :selected => 1
  %>
  <!--colocar tinymce  para Exp profissional-->
  <%= f.text_area :expProf,label: "Experiência profissional", :input_html => { :class => "textarea" } %>
  <%= f.input :localidade, label: "Localidade" %>
  <%= f.input :paginapessoal, label: "Página pessoal" %>
  <%= f.input :bi, label: "Bilhete de identificação" %>
  <%= f.input :areaprof, label: "Área profissional", as: :select,
  collection: [
  'Progamador Web',
  'Eng de software',
  'Eng de sistemas',
  'outro'],
  :selected => 3
  %>
  <!--direita-->
</div>
<%= f.button :submit %>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-6">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag(user.picture.url,size: "120x120") if user.picture?  %>
      <%if user.tipouser=='candidato'%>
      <%= image_tag("fpo_avatar.png",size: "120x120") if !user.picture?%>
      <%end%>
      <%if user.tipouser=='entidade'%>
      <%= image_tag("man.png",size: "120x120") if !user.picture?%>
      <%end%>
    </div>

    <div class="col-md-9">
    <div class="row col-md-12">

      <%= link_to user.name, user %>
    </div>

      <%if user.tipouser=='candidato'%>

      <div class="row col-md-12">
      <%=user.areaprof%>
      </div>
      <div class="row col-md-12">
      <%=user.niveldehab%>
      </div>
      <div class="row col-md-12">
      <%=user.situacaoprof%>    </div>
      <% end %>





      <%if user.tipouser=='entidade'%>
      <div class="row col-md-12">
      <%if user.offers.count > 0%>
      <%=user.offers.count%> ofertas ativas!
      <%else%>
      Não tem ofertas!
      <% end %>
      </div>
      <div class="row col-md-12">
      <%=truncate(user.apresentacao, :length => 80)%>
      </div>
      <div class="row col-md-12">
      <%=user.situacaoprof%>
      </div>
      <% end %>
      </div>

    </div>

  <br>
  <div class="row col-md-12" >
    <%if logged_in?%>


      <%if current_user.tipouser=='entidade' && user.tipouser=='candidato'%>
       <div class="col-md-6">
      <% @user=user%>
            <%= render 'follow_form' if logged_in? %>
       </div>
      <% end %>
      <%if current_user.tipouser=='candidato' && user.tipouser=='entidade'%>
       <div class="col-md-6">
           <% @user=user%>
            <%= render 'follow_form' if logged_in? %>
       </div>
      <% end %>


      <div class="col-md-3">
        <% if current_user.tipouser == "admin" && !current_user?(user) %>
        <%= link_to "Editar ",  edit_user_path(user), :class=>"btn btn-primary"%>
        <% end %>
        <% if current_user?(user) %>
        <%= link_to "Editar ",  edit_user_path(user), :class=>"btn btn-primary"%>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if current_user.tipouser=="admin" && !current_user?(user) %>
        <%=button_to  "Eliminar", user, :method => :delete, :class=>"btn btn-primary"%>
        <% end %>
      </div>
       <% end %>
    </div>


    <br>
    <br>
  </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>



<h1>All users</h1>

<div class ="row col-md-12 vert-offset-top-1 vert-offset-bottom-2">
  <div class="col-md-6 ">
<%= simple_form_for users_path, :method => 'get' do |f|%>
    <div class="input-group">
      <div class="col-md-3 ">
      <%= f.submit "Go!", :class =>"btn btn-default"%>
      </div>
      <div class="col-md-5 col-md-offset-2">
      <%= text_field_tag :containcand, params[:name], :class=>"form-control", :placeholder=>"Search for...",:type=>"text" ,label: false , :maxlength=>"15"%>
      </div>
    </div>
<%end%>
  </div>
</div>

<ul class="users">

  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/perfilent.html.erb
<div class="row">
<div class="col-md-6">

<h3>Ofertas</h3>
<div class="col-md-12">
  <% @offersAtivas.each do |f|%>
<div class="row">
    <div class="col-md-4">
      <%= image_tag(f.picture.url , size: "100x80")if f.picture?  %>
      <%= image_tag("oferta.png",size: "100x80") if !f.picture?%>
<p>      <%= link_to "Editar",  edit_offer_path(f), :class=>"btn btn-primary"%></p>
      <%=simple_form_for f do |f|%>
     <%= f.hidden_field :ativado, :value => false%>
       <%= f.button :submit,"Cancelar" , class: "btn btn-primary"%>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="col-md-12">
        <%=link_to f.title, f %>
      </div>
      <div class="col-md-12">
        <%=f.dataInicio%> - <%=f.dataFim%>
      </div>
      <div class="col-md-12">
        <%= truncate(f.content, :length => 35) %>
        Posted <%= time_ago_in_words(f.created_at) %> ago.
      </div>
    </div>
    <br>
    <br>
    <br>
</div>



  <% end %>
   <div class="col-md-12 ">
  <%= will_paginate @offersAtivas, :param_name => 'o_page'%>
  </div>
</div>


</div>



<div class="col-md-6">
<h3>Entidade</h3>
<%= link_to "Editar Perfil",  edit_user_path(current_user), :class=>"btn btn-primary"%>
<%= link_to "Alterar Password ",  editPwUser_path(current_user), :class=>"btn btn-primary"%>
<%= link_to "Inserir Nova Oferta",  offers_new_path, :class=>"btn btn-primary"%>
</div>
</div>


<div class="row">
<div class="col-md-6">
<h3>Histórico</h3>


<%if @historicoOffers.any?%>
  <% @historicoOffers.each do |f|%>
<div class="row">
    <div class="col-md-4">
      <%= image_tag(f.picture.url , size: "100x80")if f.picture?  %>
      <%= image_tag("oferta.png",size: "100x80") if !f.picture?%>
            <%=simple_form_for f do |f|%>
     <%= f.hidden_field :ativado, :value => true%>
       <%= f.button :submit,"Reativar" , class: "btn btn-primary"%>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="col-md-12">
        <%=link_to f.title, f %>
      </div>
      <div class="col-md-12">
        <%=f.dataInicio%> - <%=f.dataFim%>
      </div>
      <div class="col-md-12">
        <%= truncate(f.content, :length => 35) %>
        Posted <%= time_ago_in_words(f.created_at) %> ago.
      </div>
    </div>
    <br>
    <br>
    <br>
</div>
  <% end %>
   <div class="col-md-12">
  <%= will_paginate @historicoOffers, :param_name => 'ho_page'%>
  </div>
    <%else%>
  <h5>Não tem ofertas no histórico</h5>
  <% end %>

</div>


<div class="col-md-6">
<h3>Candidatos interessados</h3>
<%if @candinteressados.any?%>

<% @candinteressados.each do |u|%>
  <div class="col-md-12">
    <div class="col-md-3">
      <%= image_tag(u.picture.url,size: "100x80") if u.picture?  %>
      <%= image_tag("fpo_avatar.png",size: "100x80") if !u.picture?%>
    </div>
    <div class="col-md-9">
      <div class="row col-md-12">
        <%= link_to u.name, u %>
      </div>
      <div class="row col-md-12">
        <%=u.areaprof%>
      </div>
      <div class="row col-md-12">
        <%=u.niveldehab%>
      </div>
      <div class="row col-md-12">
        <%=u.situacaoprof%>
      </div>
    </div>
    <br>
  </div>
  <%end%>
     <div class="col-md-12">
  <%= will_paginate @candinteressados, :param_name => 'c_page'%>
  </div>

  <%else%>
  <h5>Não tem candidatos interessados.</h5>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<%if @user.tipouser == "candidato"%>
<%=render 'detalhesCandidato'%>
<%else%>
<%=render 'detalhesEntidade'%>
<% end %>