config/routes.rb
BolsaDeEmpApp::Application.routes.draw do
root             'static_pages#home'

#backoffice
get 'backoffice'  => 'backoffice#home'
get 'editUsers' => 'backoffice#editUsers'
get 'editNoticias' => 'backoffice#editNoticias'
get 'backofficeDetalhesUser' => 'backoffice#detalhesUser'
get 'editUser' => 'backoffice#editUser'
get 'inserirUser' => 'backoffice#inserirUser'
get 'editPw' => 'backoffice#editPw'
get 'editNoticia' => 'backoffice#editNoticia'
get 'backofficeDetalhesNoticia' => 'backoffice#detalhesNoticia'
get 'inserirNoticia' => 'backoffice#inserirNoticia'



#users
resources :users do
  member do
    get :following, :followers
    get :userCandidates
  end
end
get 'showEntidades' => 'users#showEntidades'
get 'showCandidatos' => 'users#showCandidatos'
get 'editPwUser' => 'users#editPwUser'
post 'updatePW' => 'users#updatePW'
get 'perfilent' => 'users#perfilent'
get 'perfilcand' => 'users#perfilcand'
post 'candidatosignup'  => 'users#newCandidato'
post 'entidadesignup' => 'users#newEntidade'
get 'users/new'


#session
get 'sessions/new'
get 'signup'  => 'sessions#choose'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'

#offers
resources :offers
get 'offers/new'
get 'showOfertas' => 'offers#showOfertas'

#articles
resources :articles
get 'articles/new'
get 'showNoticias'  => 'articles#showNoticias'

#relationship
resources :relationships,       only: [:create, :destroy]

#Candidatures
resources :candidatures,       only: [:create, :destroy]
get 'candidatures/new'


#account activation
resources :account_activations, only: [:edit]

#password reset
resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :admin_user
  include ApplicationHelper
def home
end
#show all editable users
def editUsers
  store_location
  @users=User.all
  @tipos=User.uniq.pluck(:tipouser).reject{ |f| f.nil? || f.empty? }
 @users = User.contain(params[:name],params[:tipo])
end

#edit a single user
def editUser
store_location
@user = User.find(params[:id])
end

def editPw
@user = User.find(params[:id])
end


def inserirUser
@user = User.new
end
def inserirNoticia
@noticia = Article.new
end

def editNoticias
store_location
@noticias = Article.order(destaque: :desc,data: :desc).containbackoffice(params[:name])
end

def editNoticia
store_location
@noticia=Article.find(params[:id])
end

def show

end

def detalhesUser
 @user = User.find(params[:id])
end

def detalhesNoticia
 @noticia = Article.find(params[:id])
end
private

# Confirms an admin user.

end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/detalhesNoticia.html.erb
<div class="row">
<div class="col-md-12">
<h3>Detalhe da Notícia</h3>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Título</b></p>
<%=@noticia.title%>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Data</b></p>
<%=@noticia.data%>
</div>


<div class="col-md-12 vert-offset-top-3">
<p><b>Sumário</b></p>
<%=@noticia.sumario%>
</div>
<div class="col-md-12 vert-offset-top-3">
<p><b>Texto</b></p>
<%=@noticia.content%>
</div>
<div class="col-md-12 vert-offset-top-3">
<p><b>Imagem</b></p>
<div class="col-md-12">
<%= image_tag @noticia.picture.url if @noticia.picture?  %>
</div>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Destaque</b></p>
<%if @noticia.destaque? %>
Sim
<%else%>
Não
<%end%>
</div>
<div class="col-md-6 vert-offset-top-3">
<p><b>Activo</b></p>
<%if @noticia.activated? %>
Sim
<%else%>
Não
<%end%>
</div>





<div class="col-md-6 vert-offset-top-3">
<%= link_to "Editar ",  {:controller => "backoffice", :action => "editNoticia", :id => @noticia.id }, :class=>"btn btn-primary"%>
<%=link_to  "Apagar", @noticia, :method => :delete, :class=>"btn btn-primary"%>
<%= link_to "Inserir ",  {:controller => "backoffice", :action => "inserirNoticia", :id => @noticia.id }, :class=>"btn btn-primary"%>
<%= link_to "Listagem ",  articles_path , :class=>"btn btn-primary"%>
</div>
</div>

app/views/backoffice/detalhesUser.html.erb
<div class="row">
<div class="col-md-12">
<h3>Detalhe do utilizador</h3>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Nome</b></p>
<%=@user.name%>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Tipo</b></p>
<%=@user.tipouser%>
</div>


<div class="col-md-6 vert-offset-top-3">
<p><b>Email</b></p>
<%=@user.email%>
</div>

<div class="col-md-6 vert-offset-top-3">
<p><b>Activo</b></p>
<%if @user.activated? %>
Sim
<%else%>
Não
<%end%>
</div>
<div class="col-md-6 vert-offset-top-3">
<%= link_to "Editar ",  {:controller => "backoffice", :action => "editUser", :id => @user.id }, :class=>"btn btn-primary"%>
<%= link_to "Alterar Password ",  {:controller => "backoffice", :action => "editPw", :id => @user.id }, :class=>"btn btn-primary"%>
<%if @user.tipouser!='admin'%>
<%=link_to  "Apagar", @user, :method => :delete, :class=>"btn btn-primary"%>
<%end%>
<%= link_to "Inserir ",  {:controller => "backoffice", :action => "inserirUser", :id => @user.id }, :class=>"btn btn-primary"%>
<%= link_to "Listagem ",  users_path , :class=>"btn btn-primary"%>
</div>
</div>

app/views/backoffice/editNoticia.html.erb
<% provide(:title, 'Edit user') %>
<%= tinymce_assets %>
<div class="row">
  <div class="col-md-4"><h3>Editar Notícia</h3></div>
</div>


<div class="row">
<%= simple_form_for @noticia, html: { multipart: true } do |f| %>

<div class="col-md-4">
<p><b>Título</b></p>
<%=f.input :title,as: :string, label: false%>
</div>
<div class="col-md-6 col-md-offset-2">
<%=f.input :data%>
</div>


<div class="col-md-12">
<%= f.input :sumario,  :as => :text, :input_html => { :class => 'tinymce'} %>
</div>

<div class="col-md-12">
<%= f.input :content,  :as => :text, :input_html => { :class => 'tinymce'} %>
</div>
<div class="col-md-12">
<%= f.input :picture, :as => :file , label: "Imagem de Perfil" %>
</div>
<div class="col-md-12">
<div class="col-md-2">
<h4>Destaque</h4>
    <%= f.input :destaque, as: :boolean, label: "Sim" %>
</div>
<div class="col-md-2 col-md-offset-2">
<h4>Activo</h4>
    <%= f.input :activated, as: :boolean, label: "Sim" %>
</div>
</div>
<div class="col-md-12">
<div class="col-md-3">
  <%= f.button :submit,"Ok" , class: " btn btn btn-primary  col-md-2"%>

  <%= link_to "Cancelar", :back, {:class=>"btn btn btn-primary "} %>
</div>
</div>
</div>
<%end%>
<%= tinymce %>

app/views/backoffice/editNoticias.html.erb
<div class ="row col-md-12">
<div class="col-md-12">
<h3>Noticias</h3>
</div>

</div>



<div class ="row col-md-12 vert-offset-top-1 vert-offset-bottom-2">

<%= simple_form_for '', :method => 'get' do |f|%>

      <div class="col-md-2 ">
      <%= f.submit "Go!", :class =>"btn btn-default"%>
      </div>
      <div class="col-md-2">
      <%= text_field_tag :name, params[:name], :class=>"form-control", :placeholder=>"Procurar por...",:type=>"text" ,label: false , :maxlength=>"15"%>


      </div>


<%end%>

</div>

<div class ="row col-md-12 vert-offset-top-1">

<div class="col-md-12">
<table class="table table-fixed">
    <thead>
      <tr>
        <th class="col-md-3">Noticia</th>
        <th class="col-md-5">Data</th>
        <th class="col-md-1">Destaque</th>
        <th class="col-md-1">Activo</th>
        <th class="col-md-2">Acções</th>
      </tr>
    </thead>
    <tbody>
<%@noticias.each do |t| %>
<tr>
        <td class="col-md-3"><%=t.title%></td>
        <td class="col-md-5"><%=t.created_at%></td>
        <%if t.destaque? %>
        <td class="col-md-1">Sim</td>
        <%else%>
        <td class="col-md-1">Não</td>
        <%end%>
        <%if t.activated? %>
        <td class="col-md-1">Sim</td>
        <%else%>
        <td class="col-md-1">Não</td>
        <%end%>
        <td class="col-md-2">
        <%= link_to "Detalhes ",  {:controller => "backoffice", :action => "detalhesNoticia", :id => t.id }, :class=>"btn btn-primary"%>
        <%= link_to "Editar ",  {:controller => "backoffice", :action => "editNoticia", :id => t.id }, :class=>"btn btn-primary"%>
        <%=link_to  "Apagar", t, :method => :delete, :class=>"btn btn-primary"%>

        </td>
</tr>
<%end%>
</tbody>

</table>

<%= link_to "Inserir Nova Noticia",  {:controller => "backoffice", :action => "inserirNoticia" }, :class=>"btn btn-primary"%>
 </div>


</div>

app/views/backoffice/editPw.html.erb
<% provide(:title, 'Edit user') %>

<div class="row">
  <div class="col-md-4"><h3>Alterar Password</h3></div>
</div>
<div class="row">
<div class="col-md-12">
<p><b>Nome:</b></p>
<%=@user.name%>
</div>
</div>

<div class="row vert-offset-top-2">
  <%= simple_form_for @user, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages' %>
  <!--campos esquerda sup-->
  <div class="col-md-4">

    <%= f.input :password, label: "Password" %>

    <%= f.input :password_confirmation, label: "Confirmação da Password" %>

  <%= f.button :submit,"Ok" , class: " btn btn btn-primary  col-md-2"%>
  <%= link_to "Cancel", :back, {:class=>"btn btn btn-primary  col-md-offset-1"} %>

  </div>


</div>





  <%end%>

app/views/backoffice/editUser.html.erb
<% provide(:title, 'Edit user') %>

<div class="row">
  <div class="col-md-4"><h3>Editar Utilizador</h3></div>
</div>
<div class="row">
  <%= simple_form_for @user, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages' %>
  <!--campos esquerda sup-->
  <div class="col-md-4">

    <%= f.input :email, label: "Email" %>

    <%= f.input :name ,label: "Nome"%>

  <%= f.button :submit,"Ok" , class: " btn btn btn-primary  col-md-2"%>
  <%= link_to "Cancel", :back, {:class=>"btn btn btn-primary  col-md-offset-1"} %>

  </div>


  <div class="col-md-2">
  <h4>Tipo</h4>
    <%= @user.tipouser%>
  <h4>Activo</h4>
    <%= f.input :activated, as: :boolean, label: "Sim" %>

  </div>
</div>





  <%end%>

app/views/backoffice/editUsers.html.erb
<div class ="row col-md-12">
<div class="col-md-12">
<h3>Utilizadores</h3>
</div>

</div>



<div class ="row col-md-12 vert-offset-top-1 vert-offset-bottom-2">

<%= simple_form_for '', :method => 'get' do |f|%>

      <div class="col-md-2 ">
      <%= f.submit "Go!", :class =>"btn btn-default"%>
      </div>
      <div class="col-md-2">
      <%= text_field_tag :name, params[:name], :class=>"form-control", :placeholder=>"Procurar por...",:type=>"text" ,label: false , :maxlength=>"15"%>


      </div>
      <div class="col-md-2">
         <%= f.input :tipo, as: :select, collection: @tipos ,label: false,prompt: 'Tipo',:include_blank => false%>

    </div>

<%end%>

</div>




<div class ="row col-md-12 vert-offset-top-1">

<div class="col-md-12">
<table class="table table-fixed">
    <thead>
      <tr>
        <th class="col-md-3">Nome</th>
        <th class="col-md-3">Tipo</th>
        <th class="col-md-3">Ativo</th>
        <th class="col-md-3">Ações</th>
      </tr>
    </thead>
    <tbody>
<%@users.each do |t| %>
<tr>
        <td class="col-md-3"><%=t.name%></td>
        <td class="col-md-3"><%=t.tipouser%></td>
        <%if t.activated? %>
        <td class="col-md-3">Sim</td>
        <%else%>
        <td class="col-md-3">Não</td>
        <%end%>
        <td class="col-md-3">
        <%= link_to "Detalhes ",  {:controller => "backoffice", :action => "detalhesUser", :id => t.id }, :class=>"btn btn-primary"%>
        <%= link_to "Editar ",  {:controller => "backoffice", :action => "editUser", :id => t.id }, :class=>"btn btn-primary"%>
      <%if t.tipouser!='admin'%>
        <%=link_to  "Apagar", t, :method => :delete, :class=>"btn btn-primary"%>
        <%else%>
        <button class="btn btn-default"> Apagar</button>
      <%end%>
        </td>
</tr>
<%end%>
</tbody>

</table>

<%= link_to "Inserir Novo Utilizador",  {:controller => "backoffice", :action => "inserirUser" }, :class=>"btn btn-primary"%>
 </div>


</div>

app/views/backoffice/inserirNoticia.html.erb
<% provide(:title, 'Edit user') %>
<%= tinymce_assets %>
<div class="row">
  <div class="col-md-4"><h3>Inserir Notícia</h3></div>
</div>


<div class="row">
<%= simple_form_for @noticia, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages_article' %>
<div class="col-md-4">
<p><b>Título</b></p>
<%=f.input :title,as: :string, label: false%>
</div>
<div class="col-md-6 col-md-offset-2">
<%=f.input :data%>
</div>


<div class="col-md-12">
<%= f.input :sumario,  :as => :text, :input_html => { :class => 'tinymce'} %>
</div>

<div class="col-md-12">
<%= f.input :content,  :as => :text, :input_html => { :class => 'tinymce'} %>
</div>
<div class="col-md-12">
<%= f.input :picture, :as => :file , label: "Imagem de Perfil" %>
</div>
<div class="col-md-12">
<div class="col-md-2">
<h4>Destaque</h4>
    <%= f.input :destaque, as: :boolean, label: "Sim" %>
</div>
<div class="col-md-2 col-md-offset-2">
<h4>Activo</h4>
    <%= f.input :activated, as: :boolean, label: "Sim" %>
</div>
</div>
<div class="col-md-12">
<div class="col-md-3">
  <%= f.button :submit,"Ok" , class: " btn btn btn-primary  col-md-2"%>

  <%= link_to "Cancelar", :back, {:class=>"btn btn btn-primary "} %>
</div>
</div>
</div>
<%end%>
<%= tinymce %>

app/views/backoffice/inserirUser.html.erb
<% provide(:title, 's') %>

<div class="row">
  <div class="col-md-4"><h3>Inserir Utilizador</h3></div>
</div>
<div class="row">
  <%= simple_form_for @user, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages' %>
  <!--campos esquerda sup-->
  <div class="col-md-4">
    <%= f.hidden_field :password, :value => 'example'%>

    <%= f.input :email, label: "Email" %>

    <%= f.input :name ,label: "Nome"%>

  <%= f.button :submit,"Ok" , class: " btn btn btn-primary  col-md-2"%>
  <%= link_to "Cancel", :back, {:class=>"btn btn btn-primary  col-md-offset-1"} %>

  </div>


  <div class="col-md-2">

  <%= f.input :tipouser, label: "Tipo", as: :select,
      collection: [
      'entidade',
      'candidato',],
      :selected => 0
      %>
    <%= @user.tipouser%>
  <h4>Activo</h4>
    <%= f.input :activated, as: :boolean, label: "Sim" %>

  </div>
</div>





  <%end%>