config/routes.rb
BolsaDeEmpApp::Application.routes.draw do
root             'static_pages#home'

#backoffice
get 'backoffice'  => 'backoffice#home'
get 'editUsers' => 'backoffice#editUsers'
get 'editNoticias' => 'backoffice#editNoticias'
get 'backofficeDetalhesUser' => 'backoffice#detalhesUser'
get 'editUser' => 'backoffice#editUser'
get 'inserirUser' => 'backoffice#inserirUser'
get 'editPw' => 'backoffice#editPw'
get 'editNoticia' => 'backoffice#editNoticia'
get 'backofficeDetalhesNoticia' => 'backoffice#detalhesNoticia'
get 'inserirNoticia' => 'backoffice#inserirNoticia'



#users
resources :users do
  member do
    get :following, :followers
    get :userCandidates
  end
end
get 'showEntidades' => 'users#showEntidades'
get 'showCandidatos' => 'users#showCandidatos'
get 'editPwUser' => 'users#editPwUser'
post 'updatePW' => 'users#updatePW'
get 'perfilent' => 'users#perfilent'
get 'perfilcand' => 'users#perfilcand'
post 'candidatosignup'  => 'users#newCandidato'
post 'entidadesignup' => 'users#newEntidade'
get 'users/new'


#session
get 'sessions/new'
get 'signup'  => 'sessions#choose'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'

#offers
resources :offers
get 'offers/new'
get 'showOfertas' => 'offers#showOfertas'

#articles
resources :articles
get 'articles/new'
get 'showNoticias'  => 'articles#showNoticias'

#relationship
resources :relationships,       only: [:create, :destroy]

#Candidatures
resources :candidatures,       only: [:create, :destroy]
get 'candidatures/new'


#account activation
resources :account_activations, only: [:edit]

#password reset
resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Portal Bolsa De Emprego", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <!-- Barra superior encostado à esquerda-->
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Entidades", showEntidades_path %></li>
        <li><%= link_to "Candidatos", showCandidatos_path %></li>
        <li><%= link_to "Ofertas", showOfertas_path %></li>
        <li><%= link_to "Noticias", showNoticias_path %></li>
      </ul>
      <!-- Barra superior encostado à direita-->
      <ul class="nav navbar-nav navbar-right">
        <% if (logged_in? ) %>


             <%if(admin?)%>
                  <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Backoffice <b class="caret"></b>
                  </a>
                    <ul class="dropdown-menu">
                    <li><%= link_to "Home", backoffice_path %></li>
                    <li><%= link_to "Utilizadores", editUsers_path %></li>
                    <li><%= link_to "Noticias", editNoticias_path %></li>
                  </ul>
                  </li>
             <%end%>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <%if (!admin?)%>
            <%if current_user.tipouser=='entidade'%>
             <li><%= link_to "Profile", perfilent_path %></li>
            <%end%>
            <%if current_user.tipouser=='candidato'%>
             <li><%= link_to "Profile", perfilcand_path %></li>
            <%end%>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Alterar Password ",  editPwUser_path(current_user)%></li>
          <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Registar-me", signup_path %></li>
        <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>